.. vim: ft=rst sts=2 sw=2 tw=70
.. default-role:: literal

Things about APIv2 that irk me
==============================

* studio should support JSON response bodies.

  personally i wouldn't mind ditching XML completely,
  but JSON should at least be provided as an option.

* same things should have same representations.

  compare `/summary/disks` vs `/health_check/disks`.

* having *most* data in elements and *some* data
  in attributes means two ways to handle data,
  the arbitrary choice adds to cognitive load,
  with no gain.
* all timestamps should use the ISO8601/RFC3339 format,
  of course in UTC.  instead of ::

    <last_pinged>2009-07-16 09:27:32 UTC</last_pinged>

  one of these would be preferable ::

    <last_pinged>2009-07-16T09:27:32Z</last_pinged>
    <last_pinged>2009-07-16T09:27:32.000Z</last_pinged>

  (`date -u '+%FT%TZ'`).

* `<since/>` elements: what is the reference point
  for the duration? ::

    <since scale="seconds">86400</since>

  there would be no ambiguity (and no attribute, so
  easier parsing) if this was given as a timestamp: ::

    <since>2009-07-16T09:27:32</since>

* `/job_history/builds` omits `<errored/>`.  it should not.
* `/health_check/mysql`: really?
